module.exports = data = [
  {
    Symbol: "AAPL",
    Name: "Apple Inc.",
    Weighting: "7.69",
    Tech: "5",
  },
  {
    Symbol: "MSFT",
    Name: "Microsoft Corporation",
    Weighting: "6.79",
    Tech: "5",
  },
  {
    Symbol: "AMZN",
    Name: "Amazon.com Inc.",
    Weighting: "3.12",
    Tech: "3",
  },
  {
    Symbol: "NVDA",
    Name: "NVIDIA Corporation",
    Weighting: "2.81",
    Tech: "5",
  },
  {
    Symbol: "GOOGL",
    Name: "Alphabet Inc. Class A",
    Weighting: "1.91",
    Tech: "5",
  },
  {
    Symbol: "TSLA",
    Name: "Tesla Inc.",
    Weighting: "1.89",
    Tech: "5",
  },
  {
    Symbol: "META",
    Name: "Meta Platform Inc.",
    Weighting: "1.70",
    Tech: "5",
  },
  {
    Symbol: "GOOG",
    Name: "Alphabet Inc.",
    Weighting: "1.66",
    Tech: "5",
  },
  {
    Symbol: "BRK.B",
    Name: "Berkshire Hathaway Inc",
    Weighting: "1.63",
    Tech: "5",
  },
  {
    Symbol: "UNH",
    Name: "UnitedHealth Group Incorporated",
    Weighting: "1.20",
    Tech: "2",
  },
  {
    Symbol: "XOM",
    Name: "Exxon Mobil Corporation",
    Weighting: "1.16",
    Tech: "5",
  },
  {
    Symbol: "JNJ",
    Name: "Johnson & Johnson",
    Weighting: "1.15",
    Tech: "1",
  },
  {
    Symbol: "JPM",
    Name: "J.P. Morgan Chase & Co.",
    Weighting: "1.14",
    Tech: "3",
  },
  {
    Symbol: "V",
    Name: "Visa Inc.",
    Weighting: "1.03",
    Tech: "5",
  },
  {
    Symbol: "LLY",
    Name: "Eli Lilly and Company",
    Weighting: "0.99",
    Tech: "5",
  },
  {
    Symbol: "AVGO",
    Name: "Broadcom Ltd",
    Weighting: "0.97",
    Tech: "5",
  },
  {
    Symbol: "PG",
    Name: "The Procter & Gamble Company",
    Weighting: "0.96",
    Tech: "3",
  },
  {
    Symbol: "MA",
    Name: "Mastercard Incorporated Class A",
    Weighting: "0.88",
    Tech: "5",
  },
  {
    Symbol: "HD",
    Name: "Home Depot, Inc.",
    Weighting: "0.84",
    Tech: "2",
  },
  {
    Symbol: "MRK",
    Name: "Merck & Co., Inc.",
    Weighting: "0.79",
    Tech: "4",
  },
  {
    Symbol: "CVX",
    Name: "Chevron Corporation",
    Weighting: "0.74",
    Tech: "1",
  },
  {
    Symbol: "PEP",
    Name: "PepsiCo, Inc.",
    Weighting: "0.68",
    Tech: "4",
  },
  {
    Symbol: "COST",
    Name: "Costco Wholesale Corporation",
    Weighting: "0.64",
    Tech: "5",
  },
  {
    Symbol: "ABBV",
    Name: "AbbVie Inc.",
    Weighting: "0.64",
    Tech: "3",
  },
  {
    Symbol: "KO",
    Name: "The Coca-Cola Company",
    Weighting: "0.63",
    Tech: "3",
  },
  {
    Symbol: "ADBE",
    Name: "Adobe Systems Incorporated",
    Weighting: "0.60",
    Tech: "3",
  },
  {
    Symbol: "WMT",
    Name: "Walmart Inc.",
    Weighting: "0.59",
    Tech: "5",
  },
  {
    Symbol: "MCD",
    Name: "McDonald's Corporation",
    Weighting: "0.59",
    Tech: "3",
  },
  {
    Symbol: "CSCO",
    Name: "Cisco Systems, Inc.",
    Weighting: "0.57",
    Tech: "2",
  },
  {
    Symbol: "PFE",
    Name: "Pfizer Inc.",
    Weighting: "0.56",
    Tech: "1",
  },
  {
    Symbol: "CRM",
    Name: "Salesforce Inc.",
    Weighting: "0.55",
    Tech: "4",
  },
  {
    Symbol: "TMO",
    Name: "Thermo Fisher Scientific Inc.",
    Weighting: "0.54",
    Tech: "3",
  },
  {
    Symbol: "NFLX",
    Name: "NetFlix Inc.",
    Weighting: "0.53",
    Tech: "3",
  },
  {
    Symbol: "BAC",
    Name: "Bank of America",
    Weighting: "0.53",
    Tech: "2",
  },
  {
    Symbol: "ACN",
    Name: "Accenture PLC",
    Weighting: "0.52",
    Tech: "4",
  },
  {
    Symbol: "ABT",
    Name: "Abbott Laboratories",
    Weighting: "0.51",
    Tech: "2",
  },
  {
    Symbol: "LIN",
    Name: "Linde Plc",
    Weighting: "0.50",
    Tech: "5",
  },
  {
    Symbol: "ORCL",
    Name: "Oracle Corporation",
    Weighting: "0.49",
    Tech: "5",
  },
  {
    Symbol: "AMD",
    Name: "Advanced Micro Devices, Inc.",
    Weighting: "0.49",
    Tech: "4",
  },
  {
    Symbol: "CMCSA",
    Name: "Comcast Corporation",
    Weighting: "0.46",
    Tech: "4",
  },
  {
    Symbol: "TXN",
    Name: "Texas Instruments Incorporated",
    Weighting: "0.44",
    Tech: "2",
  },
  {
    Symbol: "DIS",
    Name: "The Walt Disney Company",
    Weighting: "0.44",
    Tech: "1",
  },
  {
    Symbol: "WFC",
    Name: "Wells Fargo & Company",
    Weighting: "0.43",
    Tech: "2",
  },
  {
    Symbol: "DHR",
    Name: "Danaher Corporation",
    Weighting: "0.43",
    Tech: "0",
  },
  {
    Symbol: "VZ",
    Name: "Verizon Communications Inc.",
    Weighting: "0.42",
    Tech: "0",
  },
  {
    Symbol: "PM",
    Name: "Philip Morris International Inc.",
    Weighting: "0.41",
    Tech: "1",
  },
  {
    Symbol: "NEE",
    Name: "NextEra Energy, Inc.",
    Weighting: "0.40",
    Tech: "2",
  },
  {
    Symbol: "RTX",
    Name: "Raytheon Technologies Corp.",
    Weighting: "0.38",
    Tech: "2",
  },
  {
    Symbol: "HON",
    Name: "Honeywell International, Inc.",
    Weighting: "0.37",
    Tech: "4",
  },
  {
    Symbol: "INTC",
    Name: "Intel Corporation",
    Weighting: "0.37",
    Tech: "1",
  },
  {
    Symbol: "LOW",
    Name: "Lowe's Companies Inc.",
    Weighting: "0.36",
    Tech: "3",
  },
  {
    Symbol: "BMY",
    Name: "Bristol-Myers Squibb Company",
    Weighting: "0.36",
    Tech: "1",
  },
  {
    Symbol: "NKE",
    Name: "NIKE, Inc.",
    Weighting: "0.36",
    Tech: "0",
  },
  {
    Symbol: "QCOM",
    Name: "QUALCOMM Incorporated",
    Weighting: "0.36",
    Tech: "0",
  },
  {
    Symbol: "INTU",
    Name: "Intuit Inc.",
    Weighting: "0.35",
    Tech: "4",
  },
  {
    Symbol: "SPGI",
    Name: "S&P Global Inc.",
    Weighting: "0.35",
    Tech: "4",
  },
  {
    Symbol: "UPS",
    Name: "United Parcel Service, Inc.",
    Weighting: "0.35",
    Tech: "1",
  },
  {
    Symbol: "CAT",
    Name: "Caterpillar, Inc.",
    Weighting: "0.34",
    Tech: "4",
  },
  {
    Symbol: "COP",
    Name: "ConocoPhillips",
    Weighting: "0.34",
    Tech: "4",
  },
  {
    Symbol: "UNP",
    Name: "Union Pacific Corporation",
    Weighting: "0.34",
    Tech: "2",
  },
  {
    Symbol: "AMAT",
    Name: "Applied Materials, Inc.",
    Weighting: "0.33",
    Tech: "4",
  },
  {
    Symbol: "IBM",
    Name: "International Business Machines Corp.",
    Weighting: "0.33",
    Tech: "1",
  },
  {
    Symbol: "GE",
    Name: "General Electric Company",
    Weighting: "0.32",
    Tech: "5",
  },
  {
    Symbol: "ISRG",
    Name: "Intuitive Surgical, Inc.",
    Weighting: "0.32",
    Tech: "4",
  },
  {
    Symbol: "BA",
    Name: "The Boeing Company",
    Weighting: "0.32",
    Tech: "3",
  },
  {
    Symbol: "AMGN",
    Name: "Amgen Inc.",
    Weighting: "0.32",
    Tech: "0",
  },
  {
    Symbol: "SBUX",
    Name: "Starbucks Corporation",
    Weighting: "0.31",
    Tech: "4",
  },
  {
    Symbol: "NOW",
    Name: "Servicenow Inc",
    Weighting: "0.31",
    Tech: "4",
  },
  {
    Symbol: "MDT",
    Name: "Medtronic PLC",
    Weighting: "0.31",
    Tech: "1",
  },
  {
    Symbol: "MS",
    Name: "Morgan Stanley",
    Weighting: "0.30",
    Tech: "4",
  },
  {
    Symbol: "PLD",
    Name: "ProLogis",
    Weighting: "0.30",
    Tech: "3",
  },
  {
    Symbol: "T",
    Name: "AT&T Inc.",
    Weighting: "0.30",
    Tech: "0",
  },
  {
    Symbol: "GS",
    Name: "Goldman Sachs Group, Inc.",
    Weighting: "0.29",
    Tech: "3",
  },
  {
    Symbol: "DE",
    Name: "Deere & Company",
    Weighting: "0.29",
    Tech: "3",
  },
  {
    Symbol: "BLK",
    Name: "BlackRock, Inc.",
    Weighting: "0.28",
    Tech: "5",
  },
  {
    Symbol: "SYK",
    Name: "Stryker Corporation",
    Weighting: "0.28",
    Tech: "4",
  },
  {
    Symbol: "AXP",
    Name: "American Express Company",
    Weighting: "0.28",
    Tech: "4",
  },
  {
    Symbol: "ELV",
    Name: "Elevance Health Inc.",
    Weighting: "0.28",
    Tech: "2",
  },
  {
    Symbol: "LMT",
    Name: "Lockheed Martin Corporation",
    Weighting: "0.28",
    Tech: "2",
  },
  {
    Symbol: "BKNG",
    Name: "Booking Holdings Inc.",
    Weighting: "0.27",
    Tech: "5",
  },
  {
    Symbol: "MDLZ",
    Name: "Mondelez International, Inc. Class A",
    Weighting: "0.27",
    Tech: "4",
  },
  {
    Symbol: "TJX",
    Name: "The TJX Companies, Inc.",
    Weighting: "0.26",
    Tech: "4",
  },
  {
    Symbol: "GILD",
    Name: "Gilead Sciences, Inc.",
    Weighting: "0.26",
    Tech: "4",
  },
  {
    Symbol: "ADI",
    Name: "Analog Devices, Inc.",
    Weighting: "0.26",
    Tech: "4",
  },
  {
    Symbol: "MMC",
    Name: "Marsh & McLennan Companies, Inc.",
    Weighting: "0.25",
    Tech: "5",
  },
  {
    Symbol: "VRTX",
    Name: "Vertex Pharmaceuticals Incorporated",
    Weighting: "0.24",
    Tech: "4",
  },
  {
    Symbol: "ADP",
    Name: "Automatic Data Processing, Inc.",
    Weighting: "0.24",
    Tech: "3",
  },
  {
    Symbol: "AMT",
    Name: "American Tower REIT",
    Weighting: "0.24",
    Tech: "2",
  },
  {
    Symbol: "C",
    Name: "Citigroup, Inc.",
    Weighting: "0.24",
    Tech: "2",
  },
  {
    Symbol: "CVS",
    Name: "CVS Health Corp.",
    Weighting: "0.24",
    Tech: "0",
  },
  {
    Symbol: "LRCX",
    Name: "Lam Research Corporation",
    Weighting: "0.23",
    Tech: "3",
  },
  {
    Symbol: "SCHW",
    Name: "The Charles Schwab Corporation",
    Weighting: "0.23",
    Tech: "1",
  },
  {
    Symbol: "CI",
    Name: "CIGNA Group/The",
    Weighting: "0.22",
    Tech: "3",
  },
  {
    Symbol: "MO",
    Name: "Altria Group Inc.",
    Weighting: "0.22",
    Tech: "0",
  },
  {
    Symbol: "PANW",
    Name: "Palo Alto Networks Inc",
    Weighting: "0.21",
    Tech: "5",
  },
  {
    Symbol: "ETN",
    Name: "Eaton Corporation",
    Weighting: "0.21",
    Tech: "5",
  },
  {
    Symbol: "FI",
    Name: "Fiserv, Inc.",
    Weighting: "0.21",
    Tech: "5",
  },
  {
    Symbol: "TMUS",
    Name: "T-Mobile US Inc.",
    Weighting: "0.21",
    Tech: "4",
  },
  {
    Symbol: "PGR",
    Name: "The Progressive Corporation",
    Weighting: "0.21",
    Tech: "4",
  },
  {
    Symbol: "ZTS",
    Name: "Zoetis Inc.",
    Weighting: "0.21",
    Tech: "4",
  },
  {
    Symbol: "BSX",
    Name: "Boston Scientific Corporation",
    Weighting: "0.21",
    Tech: "4",
  },
  {
    Symbol: "REGN",
    Name: "Regeneron Pharmaceuticals, Inc.",
    Weighting: "0.21",
    Tech: "3",
  },
  {
    Symbol: "CB",
    Name: "Chubb Ltd",
    Weighting: "0.21",
    Tech: "1",
  },
  {
    Symbol: "EQIX",
    Name: "Equinix, Inc.",
    Weighting: "0.20",
    Tech: "4",
  },
  {
    Symbol: "BDX",
    Name: "Becton, Dickinson and Company",
    Weighting: "0.20",
    Tech: "4",
  },
  {
    Symbol: "SO",
    Name: "The Southern Company",
    Weighting: "0.20",
    Tech: "3",
  },
  {
    Symbol: "PYPL",
    Name: "Paypal Holdings Inc",
    Weighting: "0.20",
    Tech: "0",
  },
  {
    Symbol: "ITW",
    Name: "Illinois Tool Works Inc.",
    Weighting: "0.19",
    Tech: "5",
  },
  {
    Symbol: "AON",
    Name: "Aon Corporation",
    Weighting: "0.19",
    Tech: "5",
  },
  {
    Symbol: "SLB",
    Name: "Schlumberger Limited",
    Weighting: "0.19",
    Tech: "4",
  },
  {
    Symbol: "CSX",
    Name: "CSX Corporation",
    Weighting: "0.19",
    Tech: "3",
  },
  {
    Symbol: "KLAC",
    Name: "KLA Corp",
    Weighting: "0.18",
    Tech: "5",
  },
  {
    Symbol: "SNPS",
    Name: "Synopsys Inc",
    Weighting: "0.18",
    Tech: "5",
  },
  {
    Symbol: "APD",
    Name: "Air Products & Chemicals, Inc.",
    Weighting: "0.18",
    Tech: "4",
  },
  {
    Symbol: "EOG",
    Name: "EOG Resources, Inc.",
    Weighting: "0.18",
    Tech: "3",
  },
  {
    Symbol: "CME",
    Name: "CME Group, Inc.",
    Weighting: "0.18",
    Tech: "2",
  },
  {
    Symbol: "NOC",
    Name: "Northrop Grumman Systems Corporation",
    Weighting: "0.18",
    Tech: "1",
  },
  {
    Symbol: "DUK",
    Name: "Duke Energy Corporation",
    Weighting: "0.18",
    Tech: "0",
  },
  {
    Symbol: "MU",
    Name: "Micron Technology, Inc.",
    Weighting: "0.18",
    Tech: "0",
  },
  {
    Symbol: "CDNS",
    Name: "Cadence Design Systems, Inc.",
    Weighting: "0.17",
    Tech: "5",
  },
  {
    Symbol: "HCA",
    Name: "HCA Healthcare Inc.",
    Weighting: "0.17",
    Tech: "5",
  },
  {
    Symbol: "ICE",
    Name: "IntercontinentalExchange Inc.",
    Weighting: "0.17",
    Tech: "4",
  },
  {
    Symbol: "WM",
    Name: "Waste Management, Inc.",
    Weighting: "0.17",
    Tech: "3",
  },
  {
    Symbol: "SHW",
    Name: "The Sherwin-Williams Company",
    Weighting: "0.17",
    Tech: "1",
  },
  {
    Symbol: "CL",
    Name: "Colgate-Palmolive Company",
    Weighting: "0.17",
    Tech: "1",
  },
  {
    Symbol: "MCK",
    Name: "McKesson Corporation",
    Weighting: "0.16",
    Tech: "5",
  },
  {
    Symbol: "ORLY",
    Name: "O'Reilly Automotive, Inc.",
    Weighting: "0.16",
    Tech: "5",
  },
  {
    Symbol: "CMG",
    Name: "Chipotle Mexican Grill 'A'",
    Weighting: "0.16",
    Tech: "5",
  },
  {
    Symbol: "F",
    Name: "Ford Motor Company",
    Weighting: "0.16",
    Tech: "2",
  },
  {
    Symbol: "ATVI",
    Name: "Activision Blizzard, Inc.",
    Weighting: "0.16",
    Tech: "2",
  },
  {
    Symbol: "TGT",
    Name: "Target Corporation",
    Weighting: "0.16",
    Tech: "0",
  },
  {
    Symbol: "MCO",
    Name: "Moody's Corporation",
    Weighting: "0.15",
    Tech: "4",
  },
  {
    Symbol: "EW",
    Name: "Edwards Lifesciences Corporation",
    Weighting: "0.15",
    Tech: "3",
  },
  {
    Symbol: "FDX",
    Name: "FedEx Corporation",
    Weighting: "0.15",
    Tech: "3",
  },
  {
    Symbol: "HUM",
    Name: "Humana Inc.",
    Weighting: "0.15",
    Tech: "2",
  },
  {
    Symbol: "FCX",
    Name: "Freeport-McMoRan Inc.",
    Weighting: "0.15",
    Tech: "0",
  },
  {
    Symbol: "MMM",
    Name: "3M Company",
    Weighting: "0.15",
    Tech: "0",
  },
  {
    Symbol: "APH",
    Name: "Amphenol Corporation",
    Weighting: "0.14",
    Tech: "5",
  },
  {
    Symbol: "ROP",
    Name: "Roper Technologies Inc.",
    Weighting: "0.14",
    Tech: "3",
  },
  {
    Symbol: "NXPI",
    Name: "NXP Semiconductors NV",
    Weighting: "0.14",
    Tech: "3",
  },
  {
    Symbol: "EMR",
    Name: "Emerson Electric Co.",
    Weighting: "0.14",
    Tech: "1",
  },
  {
    Symbol: "GM",
    Name: "General Motors",
    Weighting: "0.14",
    Tech: "1",
  },
  {
    Symbol: "PNC",
    Name: "The PNC Financial Services Group Inc.",
    Weighting: "0.14",
    Tech: "1",
  },
  {
    Symbol: "NSC",
    Name: "Norfolk Southern Corporation",
    Weighting: "0.14",
    Tech: "0",
  },
  {
    Symbol: "FTNT",
    Name: "Fortinet Inc.",
    Weighting: "0.13",
    Tech: "5",
  },
  {
    Symbol: "PH",
    Name: "Parker-Hannifin Corporation",
    Weighting: "0.13",
    Tech: "5",
  },
  {
    Symbol: "MSI",
    Name: "Motorola Solutions Inc.",
    Weighting: "0.13",
    Tech: "5",
  },
  {
    Symbol: "DXCM",
    Name: "Dexcom Inc.",
    Weighting: "0.13",
    Tech: "5",
  },
  {
    Symbol: "AJG",
    Name: "Arthur J. Gallagher & Co.",
    Weighting: "0.13",
    Tech: "5",
  },
  {
    Symbol: "MAR",
    Name: "Marriott International, Inc.",
    Weighting: "0.13",
    Tech: "4",
  },
  {
    Symbol: "JCI",
    Name: "Johnson Controls International PLC",
    Weighting: "0.13",
    Tech: "4",
  },
  {
    Symbol: "MCHP",
    Name: "Microchip Technology Incorporated",
    Weighting: "0.13",
    Tech: "3",
  },
  {
    Symbol: "MPC",
    Name: "Marathon Petroleum Corp.",
    Weighting: "0.13",
    Tech: "3",
  },
  {
    Symbol: "GD",
    Name: "General Dynamics Corporation",
    Weighting: "0.13",
    Tech: "2",
  },
  {
    Symbol: "PXD",
    Name: "Pioneer Natural Resources",
    Weighting: "0.13",
    Tech: "2",
  },
  {
    Symbol: "CCI",
    Name: "Crown Castle Inc",
    Weighting: "0.13",
    Tech: "0",
  },
  {
    Symbol: "AZO",
    Name: "Autozone, Inc.",
    Weighting: "0.12",
    Tech: "5",
  },
  {
    Symbol: "TT",
    Name: "Trane Technologies PLC",
    Weighting: "0.12",
    Tech: "5",
  },
  {
    Symbol: "MNST",
    Name: "Monster Beverage Corp.",
    Weighting: "0.12",
    Tech: "5",
  },
  {
    Symbol: "TDG",
    Name: "TransDigm Group, Inc.",
    Weighting: "0.12",
    Tech: "5",
  },
  {
    Symbol: "CTAS",
    Name: "Cintas Corporation",
    Weighting: "0.12",
    Tech: "5",
  },
  {
    Symbol: "PCAR",
    Name: "PACCAR Inc.",
    Weighting: "0.12",
    Tech: "4",
  },
  {
    Symbol: "ADSK",
    Name: "Autodesk, Inc.",
    Weighting: "0.12",
    Tech: "3",
  },
  {
    Symbol: "KMB",
    Name: "Kimberly-Clark Corporation",
    Weighting: "0.12",
    Tech: "3",
  },
  {
    Symbol: "TEL",
    Name: "TE Connectivity Limited",
    Weighting: "0.12",
    Tech: "3",
  },
  {
    Symbol: "PSA",
    Name: "Public Storage",
    Weighting: "0.12",
    Tech: "3",
  },
  {
    Symbol: "ECL",
    Name: "Ecolab Inc.",
    Weighting: "0.12",
    Tech: "3",
  },
  {
    Symbol: "SRE",
    Name: "Sempra Energy",
    Weighting: "0.12",
    Tech: "2",
  },
  {
    Symbol: "PSX",
    Name: "Phillips 66",
    Weighting: "0.12",
    Tech: "2",
  },
  {
    Symbol: "GIS",
    Name: "General Mills, Inc.",
    Weighting: "0.12",
    Tech: "2",
  },
  {
    Symbol: "AEP",
    Name: "American Electric Power Company, Inc.",
    Weighting: "0.12",
    Tech: "1",
  },
  {
    Symbol: "USB",
    Name: "U.S. Bancorp",
    Weighting: "0.12",
    Tech: "0",
  },
  {
    Symbol: "D",
    Name: "Dominion Energy Inc.",
    Weighting: "0.12",
    Tech: "0",
  },
  {
    Symbol: "EL",
    Name: "Estee Lauder Companies",
    Weighting: "0.12",
    Tech: "0",
  },
  {
    Symbol: "WELL",
    Name: "Welltower Inc.",
    Weighting: "0.11",
    Tech: "5",
  },
  {
    Symbol: "WMB",
    Name: "Williams Companies Inc.",
    Weighting: "0.11",
    Tech: "5",
  },
  {
    Symbol: "ON",
    Name: "On Semiconductor Corp.",
    Weighting: "0.11",
    Tech: "5",
  },
  {
    Symbol: "ANET",
    Name: "Arista Networks Inc",
    Weighting: "0.11",
    Tech: "5",
  },
  {
    Symbol: "NUE",
    Name: "Nucor Corporation",
    Weighting: "0.11",
    Tech: "4",
  },
  {
    Symbol: "BIIB",
    Name: "Biogen Inc.",
    Weighting: "0.11",
    Tech: "4",
  },
  {
    Symbol: "CARR",
    Name: "Carrier Global Corp.",
    Weighting: "0.11",
    Tech: "4",
  },
  {
    Symbol: "IDXX",
    Name: "IDEXX Laboratories, Inc.",
    Weighting: "0.11",
    Tech: "4",
  },
  {
    Symbol: "COF",
    Name: "Capital One Financial Corporation",
    Weighting: "0.11",
    Tech: "4",
  },
  {
    Symbol: "OXY",
    Name: "Occidental Petroleum Corporation",
    Weighting: "0.11",
    Tech: "3",
  },
  {
    Symbol: "AIG",
    Name: "American International Group, Inc.",
    Weighting: "0.11",
    Tech: "3",
  },
  {
    Symbol: "IQV",
    Name: "IQVIA Holdings Inc.",
    Weighting: "0.11",
    Tech: "3",
  },
  {
    Symbol: "EXC",
    Name: "Exelon Corporation",
    Weighting: "0.11",
    Tech: "2",
  },
  {
    Symbol: "ADM",
    Name: "Archer-Daniels-Midland Company",
    Weighting: "0.11",
    Tech: "2",
  },
  {
    Symbol: "TRV",
    Name: "The Travelers Companies, Inc.",
    Weighting: "0.11",
    Tech: "2",
  },
  {
    Symbol: "CTVA",
    Name: "Corteva Inc",
    Weighting: "0.11",
    Tech: "2",
  },
  {
    Symbol: "O",
    Name: "Realty Income Corporation",
    Weighting: "0.11",
    Tech: "2",
  },
  {
    Symbol: "STZ",
    Name: "Constellation Brands, Inc.",
    Weighting: "0.11",
    Tech: "1",
  },
  {
    Symbol: "VLO",
    Name: "Valero Energy Corp",
    Weighting: "0.11",
    Tech: "1",
  },
  {
    Symbol: "TFC",
    Name: "Truist Financial Corp",
    Weighting: "0.11",
    Tech: "1",
  },
  {
    Symbol: "MRNA",
    Name: "Moderna, Inc.",
    Weighting: "0.11",
    Tech: "0",
  },
  {
    Symbol: "AME",
    Name: "Ametek Inc",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "DHI",
    Name: "D.R. Horton, Inc.",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "HLT",
    Name: "Hilton Worldwide Holdings Inc",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "CPRT",
    Name: "Copart Incorporated",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "GWW",
    Name: "W.W. Grainger, Inc.",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "HSY",
    Name: "The Hershey Company",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "AFL",
    Name: "AFLAC Incorporated",
    Weighting: "0.10",
    Tech: "5",
  },
  {
    Symbol: "SPG",
    Name: "Simon Property Group, Inc.",
    Weighting: "0.10",
    Tech: "4",
  },
  {
    Symbol: "CSGP",
    Name: "CoStar Group Inc.",
    Weighting: "0.10",
    Tech: "4",
  },
  {
    Symbol: "HES",
    Name: "Hess Corporation",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "PAYX",
    Name: "Paychex, Inc.",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "OTIS",
    Name: "Otis Worldwide Corporation",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "YUM",
    Name: "Yum! Brands, Inc.",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "ROST",
    Name: "Ross Stores, Inc.",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "ROK",
    Name: "Rockwell Automation, Inc.",
    Weighting: "0.10",
    Tech: "3",
  },
  {
    Symbol: "SYY",
    Name: "Sysco Corporation",
    Weighting: "0.10",
    Tech: "2",
  },
  {
    Symbol: "CHTR",
    Name: "Charter Communications, Inc.",
    Weighting: "0.10",
    Tech: "2",
  },
  {
    Symbol: "CNC",
    Name: "Centene Corporation",
    Weighting: "0.10",
    Tech: "2",
  },
  {
    Symbol: "MSCI",
    Name: "MSCI Inc.",
    Weighting: "0.10",
    Tech: "1",
  },
  {
    Symbol: "LHX",
    Name: "L3Harris Technologies Inc",
    Weighting: "0.10",
    Tech: "1",
  },
  {
    Symbol: "A",
    Name: "Agilent Technologies, Inc",
    Weighting: "0.10",
    Tech: "1",
  },
  {
    Symbol: "DG",
    Name: "Dollar General Corp.",
    Weighting: "0.10",
    Tech: "0",
  },
  {
    Symbol: "MET",
    Name: "MetLife, Inc.",
    Weighting: "0.10",
    Tech: "0",
  },
  {
    Symbol: "DOW",
    Name: "Dow, Inc.",
    Weighting: "0.10",
    Tech: "0",
  },
  {
    Symbol: "VRSK",
    Name: "Verisk Analytics, Inc.",
    Weighting: "0.09",
    Tech: "5",
  },
  {
    Symbol: "ODFL",
    Name: "Old Dominion Freight Line, Inc.",
    Weighting: "0.09",
    Tech: "5",
  },
  {
    Symbol: "AMP",
    Name: "Ameriprise Financial",
    Weighting: "0.09",
    Tech: "5",
  },
  {
    Symbol: "LEN",
    Name: "Lennar Corporation",
    Weighting: "0.09",
    Tech: "4",
  },
  {
    Symbol: "RMD",
    Name: "ResMed Inc",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "PPG",
    Name: "PPG Industries, Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "GEHC",
    Name: "GE Healthcare Technologies Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "DLR",
    Name: "Digital Realty Trust, Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "CMI",
    Name: "Cummins Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "DD",
    Name: "DuPont de Nemours Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "KMI",
    Name: "Kinder Morgan Inc.",
    Weighting: "0.09",
    Tech: "3",
  },
  {
    Symbol: "FAST",
    Name: "Fastenal Company",
    Weighting: "0.09",
    Tech: "2",
  },
  {
    Symbol: "BK",
    Name: "Bank of New York Mellon Corporation",
    Weighting: "0.09",
    Tech: "2",
  },
  {
    Symbol: "CTSH",
    Name: "Cognizant Technology Solutions",
    Weighting: "0.09",
    Tech: "1",
  },
  {
    Symbol: "XEL",
    Name: "Xcel Energy, Inc.",
    Weighting: "0.09",
    Tech: "1",
  },
  {
    Symbol: "EA",
    Name: "Electronic Arts Inc.",
    Weighting: "0.09",
    Tech: "1",
  },
  {
    Symbol: "PRU",
    Name: "Prudential Financial, Inc.",
    Weighting: "0.09",
    Tech: "1",
  },
  {
    Symbol: "NEM",
    Name: "Newmont Corp",
    Weighting: "0.09",
    Tech: "0",
  },
  {
    Symbol: "FIS",
    Name: "Fidelity National Information Services,",
    Weighting: "0.09",
    Tech: "0",
  },
  {
    Symbol: "ANSS",
    Name: "Ansys Inc",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "VICI",
    Name: "VICI Properties Inc",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "DAL",
    Name: "Delta Air Lines Inc.",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "ABC",
    Name: "AmerisourceBergen Corporation",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "RSG",
    Name: "Republic Services, Inc.",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "PWR",
    Name: "Quanta Services, Inc.",
    Weighting: "0.08",
    Tech: "5",
  },
  {
    Symbol: "DFS",
    Name: "Discover Financial Services",
    Weighting: "0.08",
    Tech: "4",
  },
  {
    Symbol: "WST",
    Name: "West Pharmaceutical Services, Inc.",
    Weighting: "0.08",
    Tech: "4",
  },
  {
    Symbol: "EFX",
    Name: "Equifax Inc.",
    Weighting: "0.08",
    Tech: "4",
  },
  {
    Symbol: "URI",
    Name: "United Rentals, Inc.",
    Weighting: "0.08",
    Tech: "4",
  },
  {
    Symbol: "BKR",
    Name: "Baker Hughes Company",
    Weighting: "0.08",
    Tech: "4",
  },
  {
    Symbol: "CEG",
    Name: "Constellation Energy Corporation",
    Weighting: "0.08",
    Tech: "3",
  },
  {
    Symbol: "ZBH",
    Name: "Zimmer Biomet Holdings",
    Weighting: "0.08",
    Tech: "3",
  },
  {
    Symbol: "VMC",
    Name: "Vulcan Materials Company",
    Weighting: "0.08",
    Tech: "3",
  },
  {
    Symbol: "MLM",
    Name: "Martin Marietta Materials In",
    Weighting: "0.08",
    Tech: "3",
  },
  {
    Symbol: "HAL",
    Name: "Halliburton Company",
    Weighting: "0.08",
    Tech: "2",
  },
  {
    Symbol: "KR",
    Name: "The Kroger Co.",
    Weighting: "0.08",
    Tech: "2",
  },
  {
    Symbol: "ED",
    Name: "Consolidated Edison, Inc.",
    Weighting: "0.08",
    Tech: "2",
  },
  {
    Symbol: "PEG",
    Name: "Public Service Enterprise Group Inc.",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "ILMN",
    Name: "Illumina, Inc.",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "DLTR",
    Name: "Dollar Tree, Inc.",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "ALL",
    Name: "The Allstate Corporation",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "DVN",
    Name: "Devon Energy Corporation",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "MTD",
    Name: "Mettler-Toledo International Inc.",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "KEYS",
    Name: "Keysight Technologies Inc",
    Weighting: "0.08",
    Tech: "1",
  },
  {
    Symbol: "KHC",
    Name: "Kraft Heinz Co/The",
    Weighting: "0.08",
    Tech: "0",
  },
  {
    Symbol: "CAH",
    Name: "Cardinal Health, Inc.",
    Weighting: "0.07",
    Tech: "5",
  },
  {
    Symbol: "IT",
    Name: "Gartner, Inc.",
    Weighting: "0.07",
    Tech: "5",
  },
  {
    Symbol: "ACGL",
    Name: "Arch Capital Group Ltd.",
    Weighting: "0.07",
    Tech: "5",
  },
  {
    Symbol: "IR",
    Name: "Ingersoll-Rand Inc.",
    Weighting: "0.07",
    Tech: "5",
  },
  {
    Symbol: "PCG",
    Name: "PG&E Corporation",
    Weighting: "0.07",
    Tech: "5",
  },
  {
    Symbol: "APTV",
    Name: "Aptiv PLC",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "TSCO",
    Name: "Tractor Supply Company",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "ALB",
    Name: "Albemarle Corp",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "CDW",
    Name: "CDW Corp.",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "CBRE",
    Name: "CBRE Group, Inc.",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "OKE",
    Name: "ONEOK, Inc.",
    Weighting: "0.07",
    Tech: "4",
  },
  {
    Symbol: "CHD",
    Name: "Church & Dwight Company",
    Weighting: "0.07",
    Tech: "3",
  },
  {
    Symbol: "ALGN",
    Name: "Align Technology, Inc.",
    Weighting: "0.07",
    Tech: "3",
  },
  {
    Symbol: "XYL",
    Name: "Xylem Inc",
    Weighting: "0.07",
    Tech: "3",
  },
  {
    Symbol: "AVB",
    Name: "AvalonBay Communities, Inc.",
    Weighting: "0.07",
    Tech: "3",
  },
  {
    Symbol: "EIX",
    Name: "Edison International",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "HPQ",
    Name: "HP Inc",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "WTW",
    Name: "Willis Towers Watson PLC",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "GLW",
    Name: "Corning Incorporated",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "WBD",
    Name: "Warner Bros. Discovery, Inc. Series A",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "FTV",
    Name: "Fortive Corp.",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "STT",
    Name: "State Street Corporation",
    Weighting: "0.07",
    Tech: "2",
  },
  {
    Symbol: "KDP",
    Name: "Keurig Dr Pepper Inc.",
    Weighting: "0.07",
    Tech: "1",
  },
  {
    Symbol: "ES",
    Name: "Eversource Energy",
    Weighting: "0.07",
    Tech: "1",
  },
  {
    Symbol: "WEC",
    Name: "WEC Energy Group Inc",
    Weighting: "0.07",
    Tech: "1",
  },
  {
    Symbol: "GPN",
    Name: "Global Payments Inc.",
    Weighting: "0.07",
    Tech: "1",
  },
  {
    Symbol: "TROW",
    Name: "T. Rowe Price Group, Inc.",
    Weighting: "0.07",
    Tech: "0",
  },
  {
    Symbol: "SBAC",
    Name: "SBA Communications Corporation",
    Weighting: "0.07",
    Tech: "0",
  },
  {
    Symbol: "AWK",
    Name: "American Water Works Company, Inc.",
    Weighting: "0.07",
    Tech: "0",
  },
  {
    Symbol: "WY",
    Name: "Weyerhaeuser Company",
    Weighting: "0.07",
    Tech: "0",
  },
  {
    Symbol: "HIG",
    Name: "The Hartford Financial Services Group",
    Weighting: "0.06",
    Tech: "5",
  },
  {
    Symbol: "RCL",
    Name: "Royal Caribbean Cruises Ltd.",
    Weighting: "0.06",
    Tech: "5",
  },
  {
    Symbol: "MPWR",
    Name: "Monolithic Power Systems Inc.",
    Weighting: "0.06",
    Tech: "5",
  },
  {
    Symbol: "VRSN",
    Name: "VeriSign, Inc.",
    Weighting: "0.06",
    Tech: "4",
  },
  {
    Symbol: "TTWO",
    Name: "Take-Two Interactive Software, Inc.",
    Weighting: "0.06",
    Tech: "4",
  },
  {
    Symbol: "HPE",
    Name: "Hewlett Packard Enterprise Company",
    Weighting: "0.06",
    Tech: "4",
  },
  {
    Symbol: "STE",
    Name: "STERIS PLC",
    Weighting: "0.06",
    Tech: "4",
  },
  {
    Symbol: "LH",
    Name: "Laboratory Corp. of America Holdings",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "FANG",
    Name: "Diamondback Energy Inc",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "ULTA",
    Name: "Ulta Beauty, Inc.",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "GPC",
    Name: "Genuine Parts Company",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "DOV",
    Name: "Dover Corporation",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "MKC",
    Name: "McCormick & Company, Incorporated",
    Weighting: "0.06",
    Tech: "3",
  },
  {
    Symbol: "LYB",
    Name: "LyondellBasell Industries NV",
    Weighting: "0.06",
    Tech: "2",
  },
  {
    Symbol: "LUV",
    Name: "Southwest Airlines Co.",
    Weighting: "0.06",
    Tech: "2",
  },
  {
    Symbol: "DTE",
    Name: "DTE Energy Company",
    Weighting: "0.06",
    Tech: "2",
  },
  {
    Symbol: "ENPH",
    Name: "Enphase Energy Inc",
    Weighting: "0.06",
    Tech: "2",
  },
  {
    Symbol: "FE",
    Name: "FirstEnergy Corp.",
    Weighting: "0.06",
    Tech: "2",
  },
  {
    Symbol: "AEE",
    Name: "Ameren Corporation",
    Weighting: "0.06",
    Tech: "1",
  },
  {
    Symbol: "MTB",
    Name: "M & T Bank Corp",
    Weighting: "0.06",
    Tech: "0",
  },
  {
    Symbol: "EQR",
    Name: "Equity Residential",
    Weighting: "0.06",
    Tech: "0",
  },
  {
    Symbol: "ETR",
    Name: "Entergy Corporation",
    Weighting: "0.06",
    Tech: "0",
  },
  {
    Symbol: "EBAY",
    Name: "eBay Inc.",
    Weighting: "0.06",
    Tech: "0",
  },
  {
    Symbol: "BAX",
    Name: "Baxter International Inc.",
    Weighting: "0.06",
    Tech: "0",
  },
  {
    Symbol: "DRI",
    Name: "Darden Restaurants, Inc.",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "CCL",
    Name: "Carnival Corporation",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "TRGP",
    Name: "Targa Resources Corp.",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "CLX",
    Name: "The Clorox Company",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "HWM",
    Name: "Howmet Aerospace Inc.",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "LVS",
    Name: "Las Vegas Sands Corp.",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "OMC",
    Name: "Omnicom Group Inc.",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "FICO",
    Name: "Fair, Isaac & Company, Incorporated",
    Weighting: "0.05",
    Tech: "5",
  },
  {
    Symbol: "UAL",
    Name: "United Airlines Holdings Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "FLT",
    Name: "Fleetcor Technologies",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "STLD",
    Name: "Steel Dynamics Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "TYL",
    Name: "Tyler Technologies, Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "HOLX",
    Name: "Hologic Incorporated",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "NVR",
    Name: "NVR, Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "PHM",
    Name: "PulteGroup, Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "VTR",
    Name: "Ventas, Inc.",
    Weighting: "0.05",
    Tech: "4",
  },
  {
    Symbol: "CNP",
    Name: "Centerpoint Energy, Inc.",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "MOH",
    Name: "Molina Healthcare Inc.",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "BR",
    Name: "Broadridge Financial Solutions Inc.",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "WAB",
    Name: "Wabtec Inc.",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "TDY",
    Name: "Teledyne Technologies Incorporated",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "RJF",
    Name: "Raymond James Financial Inc",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "COO",
    Name: "The Cooper Companies, Inc.",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "MAA",
    Name: "Mid America Apartment CMMTYS",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "PODD",
    Name: "Insulet Corporation",
    Weighting: "0.05",
    Tech: "3",
  },
  {
    Symbol: "FSLR",
    Name: "First Solar, Inc.",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "NDAQ",
    Name: "The Nasdaq Inc.",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "PPL",
    Name: "PPL Corporation",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "INVH",
    Name: "Invitation Homes Inc",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "EXPD",
    Name: "Expeditors Intl. of Washington, Inc.",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "SWKS",
    Name: "Skyworks Solutions, Inc.",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "PFG",
    Name: "Principal Financial Group",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "EXR",
    Name: "Extra Space Storage Inc.",
    Weighting: "0.05",
    Tech: "2",
  },
  {
    Symbol: "FITB",
    Name: "Fifth Third Bancorp",
    Weighting: "0.05",
    Tech: "1",
  },
  {
    Symbol: "BALL",
    Name: "Ball Corporation",
    Weighting: "0.05",
    Tech: "1",
  },
  {
    Symbol: "CMS",
    Name: "CMS Energy Corporation",
    Weighting: "0.05",
    Tech: "1",
  },
  {
    Symbol: "TER",
    Name: "Teradyne, Inc.",
    Weighting: "0.05",
    Tech: "1",
  },
  {
    Symbol: "WBA",
    Name: "Walgreens Boots Alliance Inc.",
    Weighting: "0.05",
    Tech: "0",
  },
  {
    Symbol: "CTRA",
    Name: "Coterra Energy Inc.",
    Weighting: "0.05",
    Tech: "0",
  },
  {
    Symbol: "IFF",
    Name: "International Flavors & Fragrances Inc.",
    Weighting: "0.05",
    Tech: "0",
  },
  {
    Symbol: "K",
    Name: "Kellogg Company",
    Weighting: "0.05",
    Tech: "0",
  },
  {
    Symbol: "ARE",
    Name: "Alexandria Real Estate Equities, Inc.",
    Weighting: "0.05",
    Tech: "0",
  },
  {
    Symbol: "LW",
    Name: "Lamb Weston Holdings Inc",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "AVY",
    Name: "Avery Dennison Corporation",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "SNA",
    Name: "Snap-on Incorporated",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "NDSN",
    Name: "Nordson Corporation",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "IPG",
    Name: "The Interpublic Group of Companies, Inc.",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "BRO",
    Name: "Brown & Brown, Inc.",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "PTC",
    Name: "PTC Inc",
    Weighting: "0.04",
    Tech: "5",
  },
  {
    Symbol: "EQT",
    Name: "EQT Corporation",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "IRM",
    Name: "Iron Mountain Inc.",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "MGM",
    Name: "MGM Resorts International",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "AXON",
    Name: "Axon Enterprise Inc.",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "LKQ",
    Name: "LKQ Corporation",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "ATO",
    Name: "Atmos Energy Corp",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "EG",
    Name: "Everest Group, Ltd.",
    Weighting: "0.04",
    Tech: "4",
  },
  {
    Symbol: "ZBRA",
    Name: "Zebra Technologies Corp",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "BG",
    Name: "Bunge Limited",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "CF",
    Name: "CF Industries Holdings, Inc.",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "MRO",
    Name: "Marathon Oil Corporation",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "CBOE",
    Name: "CBOE Global Markets Inc.",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "FDS",
    Name: "FactSet Research Systems Inc.",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "KMX",
    Name: "Carmax Group",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "AKAM",
    Name: "Akamai Technologies, Inc.",
    Weighting: "0.04",
    Tech: "3",
  },
  {
    Symbol: "POOL",
    Name: "Pool Corporation",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "TXT",
    Name: "Textron Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "AES",
    Name: "The AES Corporation",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "UDR",
    Name: "UDR, Inc",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "RF",
    Name: "Regions Financial Corporation",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "SWK",
    Name: "Stanley Black & Decker, Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "J",
    Name: "Jacobs Engineering Group Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "BBY",
    Name: "Best Buy Co., Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "SJM",
    Name: "The J.M. Smucker Company",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "IEX",
    Name: "IDEX Corporation",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "GRMN",
    Name: "Garmin Ltd.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "DGX",
    Name: "Quest Diagnostics Incorporated",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "EXPE",
    Name: "Expedia Group Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "TRMB",
    Name: "Trimble Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "NTAP",
    Name: "NetApp, Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "CINF",
    Name: "Cincinnati Financial Corporation",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "JBHT",
    Name: "J.B. Hunt Transport Services, Inc.",
    Weighting: "0.04",
    Tech: "2",
  },
  {
    Symbol: "LNT",
    Name: "Alliant Energy Corporation",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "PAYC",
    Name: "Paycom Software Inc",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "FMC",
    Name: "FMC Corporation",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "SEDG",
    Name: "Solaredge Technologies",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "HBAN",
    Name: "Huntington Bancshares Incorporated",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "SYF",
    Name: "Synchrony Financial",
    Weighting: "0.04",
    Tech: "1",
  },
  {
    Symbol: "EVRG",
    Name: "Evergy Inc",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "ESS",
    Name: "Essex Property Trust Inc",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "TSN",
    Name: "Tyson Foods, Inc.",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "CAG",
    Name: "Conagra Brands Inc.",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "RVTY",
    Name: "Revvity Inc.",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "AMCR",
    Name: "Amcor PLC",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "NTRS",
    Name: "Northern Trust Corporation",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "WAT",
    Name: "Waters Corporation",
    Weighting: "0.04",
    Tech: "0",
  },
  {
    Symbol: "TAP",
    Name: "Molson Coors Company",
    Weighting: "0.03",
    Tech: "5",
  },
  {
    Symbol: "TPR",
    Name: "Tapestry Inc.",
    Weighting: "0.03",
    Tech: "5",
  },
  {
    Symbol: "UHS",
    Name: "Universal Health Services, Inc.",
    Weighting: "0.03",
    Tech: "5",
  },
  {
    Symbol: "WYNN",
    Name: "Wynn Resorts, Limited",
    Weighting: "0.03",
    Tech: "5",
  },
  {
    Symbol: "ALLE",
    Name: "Allegion PLC",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "LYV",
    Name: "Live Nation Entertainment Inc.",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "AAL",
    Name: "American Airlines Group Inc.",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "KIM",
    Name: "Kimco Realty Corporation",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "JNPR",
    Name: "Juniper Networks, Inc.",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "GL",
    Name: "Globe Life Inc",
    Weighting: "0.03",
    Tech: "4",
  },
  {
    Symbol: "BWA",
    Name: "BorgWarner Inc.",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "CE",
    Name: "Celanese Corporation",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "PNR",
    Name: "Pentair Inc",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "TFX",
    Name: "Teleflex Incorporated",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "L",
    Name: "Loews Corporation",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "STX",
    Name: "Seagate Technology",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "ROL",
    Name: "Rollins, Inc.",
    Weighting: "0.03",
    Tech: "3",
  },
  {
    Symbol: "APA",
    Name: "Apache Corporation",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "CPT",
    Name: "Camden Property Trust",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "WRB",
    Name: "W. R. Berkley Corporation",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "CRL",
    Name: "Charles River Lab. Internat'l, Inc.",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "JKHY",
    Name: "Jack Henry & Associates Inc",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "BF.B",
    Name: "Brown-Forman Corporation CL B",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "TECH",
    Name: "Bio-Techne Corporation",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "MAS",
    Name: "Masco Corporation",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "MTCH",
    Name: "Match Group, Inc.",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "QRVO",
    Name: "Qorvo Inc.",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "CZR",
    Name: "Caesars Entertainment Inc.",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "REG",
    Name: "Regency Centers Corporation",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "NI",
    Name: "Nisource, Inc.",
    Weighting: "0.03",
    Tech: "2",
  },
  {
    Symbol: "CFG",
    Name: "Citizens Financial Group Inc",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "MKTX",
    Name: "MarketAxess Holdings Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "EMN",
    Name: "Eastman Chemical Company",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "HST",
    Name: "Host Hotels & Resorts Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "WDC",
    Name: "Western Digital Corporation",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "PKG",
    Name: "Packaging Corp of America",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "HSIC",
    Name: "Henry Schein, Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "CHRW",
    Name: "C.H. Robinson Worldwide, Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "CDAY",
    Name: "Ceridian HCM Holding, Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "DPZ",
    Name: "Domino's Pizza, Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "LDOS",
    Name: "Leidos Holdings Inc.",
    Weighting: "0.03",
    Tech: "1",
  },
  {
    Symbol: "INCY",
    Name: "Incyte Genomics, Inc.",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "IP",
    Name: "International Paper Company",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "EPAM",
    Name: "Epam Systems Inc",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "HRL",
    Name: "Hormel Foods Corporation",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "VTRS",
    Name: "Viatris Inc",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "GEN",
    Name: "Gen Digital Inc.",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "MOS",
    Name: "Mosaic Company",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "PEAK",
    Name: "Healthpeak Properties Inc.",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "ETSY",
    Name: "Etsy Inc",
    Weighting: "0.03",
    Tech: "0",
  },
  {
    Symbol: "NCLH",
    Name: "Norwegian Cruise Line Holdings Ltd.",
    Weighting: "0.02",
    Tech: "5",
  },
  {
    Symbol: "BBWI",
    Name: "Bath & Body Works Inc.",
    Weighting: "0.02",
    Tech: "4",
  },
  {
    Symbol: "GNRC",
    Name: "Generac Holdings, Inc.",
    Weighting: "0.02",
    Tech: "4",
  },
  {
    Symbol: "NWSA",
    Name: "News Corp. Class A",
    Weighting: "0.02",
    Tech: "4",
  },
  {
    Symbol: "RHI",
    Name: "Robert Half International Inc.",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "FRT",
    Name: "Federal Realty Investment Trust",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "PNW",
    Name: "Pinnacle West Capital Corporation",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "ALK",
    Name: "Alaska Air Group Inc",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "BEN",
    Name: "Franklin Resources, Inc.",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "HAS",
    Name: "Hasbro, Inc.",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "XRAY",
    Name: "DENTSPLY SIRONA Inc.",
    Weighting: "0.02",
    Tech: "3",
  },
  {
    Symbol: "CTLT",
    Name: "Catalent Inc.",
    Weighting: "0.02",
    Tech: "2",
  },
  {
    Symbol: "AOS",
    Name: "A.O. Smith Corporation",
    Weighting: "0.02",
    Tech: "2",
  },
  {
    Symbol: "NRG",
    Name: "NRG Energy, Inc.",
    Weighting: "0.02",
    Tech: "2",
  },
  {
    Symbol: "FFIV",
    Name: "F5 Inc.",
    Weighting: "0.02",
    Tech: "2",
  },
  {
    Symbol: "WHR",
    Name: "Whirlpool Corporation",
    Weighting: "0.02",
    Tech: "1",
  },
  {
    Symbol: "DXC",
    Name: "DXC Technology Co",
    Weighting: "0.02",
    Tech: "1",
  },
  {
    Symbol: "BXP",
    Name: "Boston Properties",
    Weighting: "0.02",
    Tech: "1",
  },
  {
    Symbol: "FOXA",
    Name: "Fox Corporation Class A",
    Weighting: "0.02",
    Tech: "1",
  },
  {
    Symbol: "HII",
    Name: "Huntington Ingalls Industries Inc",
    Weighting: "0.02",
    Tech: "1",
  },
  {
    Symbol: "PARA",
    Name: "Paramount Global",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "AIZ",
    Name: "Assurant, Inc.",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "BIO",
    Name: "Bio-Rad Laboratories, Inc. Cl. A",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "VFC",
    Name: "V.F. Corporation",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "CPB",
    Name: "Campbell Soup Company",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "WRK",
    Name: "WestRock Co",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "KEY",
    Name: "KeyCorp",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "SEE",
    Name: "Sealed Air Corporation",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "IVZ",
    Name: "Invesco PLC",
    Weighting: "0.02",
    Tech: "0",
  },
  {
    Symbol: "RL",
    Name: "Ralph Lauren",
    Weighting: "0.01",
    Tech: "4",
  },
  {
    Symbol: "DVA",
    Name: "DaVita, Inc.",
    Weighting: "0.01",
    Tech: "3",
  },
  {
    Symbol: "NWS",
    Name: "News Corp. Class B",
    Weighting: "0.01",
    Tech: "3",
  },
  {
    Symbol: "ZION",
    Name: "Zions Bancorporation",
    Weighting: "0.01",
    Tech: "2",
  },
  {
    Symbol: "LNC",
    Name: "Lincoln National Corporation",
    Weighting: "0.01",
    Tech: "2",
  },
  {
    Symbol: "CMA",
    Name: "Comerica Incorporated",
    Weighting: "0.01",
    Tech: "2",
  },
  {
    Symbol: "FOX",
    Name: "Fox Corporation Class B",
    Weighting: "0.01",
    Tech: "1",
  },
  {
    Symbol: "MHK",
    Name: "Mohawk Industries, Inc.",
    Weighting: "0.01",
    Tech: "1",
  },
  {
    Symbol: "OGN",
    Name: "Organon & Co.",
    Weighting: "0.01",
    Tech: "0",
  },
  {
    Symbol: "AAP",
    Name: "Advance Auto Parts, Inc.",
    Weighting: "0.01",
    Tech: "0",
  },
  {
    Symbol: "NWL",
    Name: "Newell Brands Inc.",
    Weighting: "0.01",
    Tech: "0",
  },
];
